name: Publish library  

permissions:
  contents: write

on:
  push:
     tags:        
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Write release version
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo Version: $VERSION
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Restore dependencies
      run: dotnet restore src/TheChest.Tests.Common
    - name: Build project
      run: dotnet build src/TheChest.Tests.Common --no-restore --configuration Release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: ${{ github.ref_name }}
        path: 'src/TheChest.Tests.Common/bin/Release/netstandard2.1'
        retention-days: 14
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.2.1
        with:
          name: ${{ github.ref_name }}
          path: 'src/TheChest.Tests.Common/bin/Release/netstandard2.1'
      - name: Restore dependencies
        run: dotnet restore src/TheChest.Tests.Common
      - name: Pack library
        run: dotnet pack src/TheChest.Tests.Common --configuration Release /p:Version=${VERSION} --no-build --output .
      - name: Push library to Github Packages
        run: dotnet nuget push TheChest.Tests.Common.${VERSION}.nupkg --source https://nuget.pkg.github.com/The-Chest/index.json --api-key "${{secrets.GH_NUGET_APIKEY}}"
      - name: Upload release attachment
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');

            const tag = context.ref.replace("refs/tags/", "");
            const version = tag.replace("v", "");
            
            const release = await github.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag
            });
            
            const dllName = `TheChest.Tests.Common.dll`;
            await github.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id,
              name: dllName,
              data: fs.readFileSync(`src/TheChest.Tests.Common/bin/Release/netstandard2.1/${dllName}`)
            });
